stages:
  - build
  - test

build_job:
  stage: build
  script:
    - mkdir -p build
    - echo "Hello, GitLab CI/CD!" > build/output.txt
  artifacts:
    paths:
      - build/output.txt

test_job:
  stage: test
  script:
    - cat build/output.txt
